### ISSUE TITLE
UNISIM.BUFGMUX_CTRL missing

### ISSUE THREAD

**Issue by p-kuzmanovic** [nickg/nvc#1037]
It seems that NVC does not support Xilinx primitive `UNISIM.BUFGMUX_CTRL`. This is a special case of a more generic `UNISIM.BUFGCTRL` component:
https://docs.amd.com/r/en-US/am003-versal-clocking-resources/BUFGMUX_CTRL

Could this be added? Was it intentionally left out?

**Comment by nickg** [comment]
I think it's because that's in the `unisims/retarget` directory and we only analyse the `unisims/primitive` directory at the moment.
