### ISSUE TITLE
Crash with type in interface of generic function.

### ISSUE THREAD

**Issue by NikLeberg** [nickg/nvc#1108]
In [#0e0181a](https://github.com/nickg/nvc/commit/0e0181af2ae72fd811192ae33dc223da59fce273) _Raise error when parameter list contains type interface declaration_ you made types in interface parameters an error (as expected according to the standard) as discussed in https://github.com/nickg/nvc/pull/1083#issuecomment-2513937973.

With the following MWE I get this error but also a crash:
```vhd
package genfact is
    function fact generic (
        function foo(type t) return natural
    ) return natural;
end package;
```

It seems to crash because the implicit `=` and `/=` functions for the type get added as generic ports. But because it is not a generic port it crashes?

One way to fix this could be the following:
```diff
diff --git a/src/parse.c b/src/parse.c
index 8a0ed211..1ff44275 100644
--- a/src/parse.c
+++ b/src/parse.c
@@ -5523,7 +5523,8 @@ static void p_interface_type_declaration(tree_t parent, tree_kind_t kind)
    tree_set_subkind(d, PORT_IN);
 
    add_interface(parent, d, kind);
-   sem_check(d, nametab);
+   if (!sem_check(d, nametab))
+      return;
 
    // Type generics are immediately visible
    insert_name(nametab, d, NULL);
```

With the early return the call to `declare_generic_ops` is skipped and we don't crash. But I don't think you'd like to "use" the return value of `sem_check` in the parser itself.

Alternatively I thought about something like `is_generic_container` or so with which we then can skip it as well.

Nothing was really satisfying for me so I thought maybe you have a better idea. 🤷‍♂️

**Comment by nickg** [comment]
I think the following should work.

```diff
diff --git a/src/parse.c b/src/parse.c
index 8a0ed2112dfc..cc40ce34afde 100644
--- a/src/parse.c
+++ b/src/parse.c
@@ -5533,7 +5533,8 @@ static void p_interface_type_declaration(tree_t parent, tree_kind_t kind)
    // immediately following the interface type declaration in the
    // enclosing interface list

-   declare_generic_ops(parent, type);
+   if (kind == T_GENERIC_DECL)
+      declare_generic_ops(parent, type);
 }

 static void p_formal_parameter_list(tree_t decl, type_t type)
```
I.e. only call `declare_generic_ops` only when parsing a generic list.
