### ISSUE TITLE
assert failure during run

### ISSUE THREAD

**Issue by fmhess** [nickg/nvc#116]
The following test program aborts when run, due to a failure to allocate a driver for the aliased bit intstat(7) (which can be seen in the vcode).

$ nvc -r nvc_bug2
nvc: ../src/rt/rtkern.c:1624: rt_sched_driver: Assertion `driver != group->n_drivers' failed.

```
library IEEE;
use IEEE.std_logic_1164.all;

entity nvc_bug2 is
end nvc_bug2;
     
architecture behav of nvc_bug2 is

  signal intstat         : STD_LOGIC_VECTOR (7 DOWNTO 0);
  ALIAS  INT_int            : STD_LOGIC is intstat(7);

begin
  
  INT_int <= '1' when (intstat(6 downto 0) and "1111111") /= "0000000";
  
  process
  begin
    intstat(6 downto 0) <= "0000000";
    wait;
  end process;
end behav;
```

If the ALIAS is not used, then the vcode does show a driver allocation for intstat(7) and there is no assertion failure.

**Comment by nickg** [comment]
Should be fixed now
