### ISSUE TITLE
FYI: ArchLinux AUR package (nvc-git)

### ISSUE THREAD

**Issue by uffejakobsen** [nickg/nvc#156]
Hi,
FYI: ArchLinux AUR package (nvc-git) can be found here:
https://aur.archlinux.org/packages/nvc-git

This "case" can be closed immediatly :-)

**Comment by nickg** [comment]
Cool, thanks. Is there some `apt-get` equivalent command I can add to the readme?

**Comment by uffejakobsen** [comment]
Not really AUR (Arch User Repository) is a sort like FreeBSD Ports - see https://wiki.archlinux.org/index.php/Arch_User_Repository
AUR only contains build descriptions - that can be manually downloaded and built with makepkg.
But I would recommend non-standard helpers such as "yaourt" or "pacaur" - they handle downloading and builds as a whole operation
