### ISSUE TITLE
bootstrap in cygwin fails

### ISSUE THREAD

**Issue by michg** [nickg/nvc#190]
With the latest llvm-llc from cygwin (3.5)  there seems to be a change in the suffix of the object files from
.o to .obj. This leads to failure at the building of the libs:
![llc-error](https://cloud.githubusercontent.com/assets/3878262/7655954/9398584a-fb27-11e4-88f6-6d78b6fc8bab.jpg)

**Comment by nickg** [comment]
I don't have access to a Windows PC at the moment - can you see if the above commit fixes it?

**Comment by michg** [comment]
Thanks Nick, works fine on Cygwin-32bit on win7.
