### ISSUE TITLE
Memory corruption bug

### ISSUE THREAD

**Issue by forrestv** [nickg/nvc#207]
I'm seeing a signal's value (specifically a value within a record within an array within an entity-level record) get corrupted in between it being written, the process being suspended, and it being read again. Any pointers on how to debug something like this?

**Comment by postoroniy** [comment]
it'd be better to check and reproduce from source code rather than analyse your complain.

**Comment by nickg** [comment]
I might be helpful to run the simulation with `--trace` and then grep out the interesting signals and post the output here?

**Comment by nickg** [comment]
I just fixed something that might cause this behaviour. Can you test again? You'll need to do a `make clean` to rebuild the IEEE libraries.

**Comment by nickg** [comment]
I think this was probably fixed by the above. Please reopen if not.
