### ISSUE TITLE
prctl: Invalid argument

### ISSUE THREAD

**Issue by jpidancet** [nickg/nvc#213]
Each invocation of nvc prints the following error message: `prctl: Invalid argument`. It appears to be non-fatal but it is polluting the rest of the output.

I'm using a vanilla 3.16.1 linux kernel.

It seems to be caused by the following code in src/util.c:

```
if (prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0) < 0)
    perror("prctl");
```

The prctl man page says:
```
       PR_SET_PTRACER (since Linux 3.4)
              This is meaningful only when the Yama LSM is enabled and in
              mode 1 ("restricted ptrace", visible via
              /proc/sys/kernel/yama/ptrace_scope).
```

The linux Yama security module doesn't seem to be present in standard configurations. Does it make sense to make prctl fail silently here ?

**Comment by nickg** [comment]
I think this was added for recent versions of Debian and Ubuntu which presumably have this enabled. Anyway the failure is harmless as you say and I've removed the message.
