### ISSUE TITLE
cast to pointer from integer of different size

### ISSUE THREAD

**Issue by hiyuh** [nickg/nvc#280]
maybe, recent gcc/llvm update to 5.3.0/3.7.1 for cygwin, now i got,
```
src/rt/jit.c: In function ‘jit_var_ptr’:
src/rt/jit.c:137:19: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       void *ptr = (void *)LLVMGetGlobalValueAddress(exec_engine, name);
                   ^
```
maybe, b/c on x86, `void *` is 32bit but `LLVMGetGlobalValueAddress()` returns `uint64_t`?

**Comment by nickg** [comment]
I think it needs to be `(void *)(uintptr_t)LLVMGetGlobalValueAddress(..)`
