### ISSUE TITLE
fetch-ieee.sh downloads HTTP URLs and does not checksum them

### ISSUE THREAD

**Issue by MikeMcQuaid** [nickg/nvc#295]
This makes this script extremely vulnerable to MITM attacks on e.g. uncontrolled WiFi networks or the upstream servers being hacked and in either case the files being replaced with malicious versions.

**Comment by MikeMcQuaid** [comment]
Suggestion: hardcode the SHA-256 checksums and check them after downloading and use an HTTPS source URL.

**Comment by nickg** [comment]
This was fixed by @robertgzr above

**Comment by MikeMcQuaid** [comment]
Thanks!
