### ISSUE TITLE
missing comma in configure.ac check for libdw

### ISSUE THREAD

**Issue by fmhess** [nickg/nvc#358]
<pre>
From 1397d8da6652d8e920b845efd2c53a10373d7f77 Mon Sep 17 00:00:00 2001
From: Frank Mori Hess <fmh6jj@gmail.com>
Date: Sun, 19 Nov 2017 19:46:08 -0500
Subject: [PATCH] Added missing comma in check for libdw.

---
 configure.ac | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/configure.ac b/configure.ac
index 485af94a..a9966b85 100644
--- a/configure.ac
+++ b/configure.ac
@@ -165,7 +165,7 @@ case $host_os in
   linux*)
     PKG_CHECK_EXISTS([libdw],
       [PKG_CHECK_MODULES([libdw], [libdw >= 0.159], [], [])
-       AC_DEFINE_UNQUOTED([HAVE_LIBDW], [1], [Have libdw for stack traces])]
+       AC_DEFINE_UNQUOTED([HAVE_LIBDW], [1], [Have libdw for stack traces])],
       [AC_MSG_NOTICE(libdw not found - using basic stack traces)])
     ;;
 esac
-- 
2.11.0
</pre>

**Comment by nickg** [comment]
I applied it,  thanks.
