### ISSUE TITLE
libexecinfo not found during configuration on openBSD

### ISSUE THREAD

**Issue by zuernerd** [nickg/nvc#379]
When trying to configure on openBSD 6.3 i get:
 
> checking for library containing backtrace_symbols... no
> configure: error: libexecinfo not found

altough i have libexecinfo installed

**Comment by nickg** [comment]
Can you post the `config.log` from the directory where you ran `configure`?

**Comment by nickg** [comment]
In the log above it finds the header file now but not the library file. Try adding these arguments to `configure`: `CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"`

**Comment by zuernerd** [comment]
Compiling went well but i have not tested whether it works. 
Thank you !!
