### ISSUE TITLE
cant open .fst in gtkwave

### ISSUE THREAD

**Issue by zuernerd** [nickg/nvc#380]
I get following errors with .fst files in gtk wave:
```
GTKWave Analyzer v3.3.86 (w)1999-2017 BSI

GTKWAVE | Could not initialize 'counter_tb.fst', exiting.
```
although im on >v3.3.53

**Comment by nickg** [comment]
Hi, can you upload the FST file you generated? I just check I can open a generated FST file with 3.3.79.
