### ISSUE TITLE
warning during execution 

### ISSUE THREAD

**Issue by kamalovicher** [nickg/nvc#382]
** Warning: cannot represent arrays of type IEEE.STD_LOGIC_1164.STD_LOGIC_VECTOR
          in FST format
and i am trying to execute this code for an encoding8b/10b existing in this web site https://github.com/freecores/8b10b_encdec  the execution doesn't stop

**Comment by nickg** [comment]
The 1.6 release has a `--dump-arrays` option you can use to dump arrays of arrays to the FST file. That particular simulation doesn't stop because it generates a clock signal indefinitely. You have to use the `--stop-time` argument in that case.
