### ISSUE TITLE
"make install" no such file or directory with msys2

### ISSUE THREAD

**Issue by dwRchyngqxs** [nickg/nvc#394]
On windows with msys2, `make install` produces several errors of `/usr/bin/install` like the following:
`'./lib/ieee/_IEEE.NUMERIC_STD.a': No such file or directory`

In lib/ieee there is _IEEE.NUMERIC_STD.**obj** but not the .a
Also I looked at the library automakefiles and there is .a and .so in filenames
It seems like nvc produces .obj and .dll files where make expects .a and .so

**Comment by nickg** [comment]
Thanks for reporting, should be fixed now.
