### ISSUE TITLE
nvc 1.5.2 test failure

### ISSUE THREAD

**Issue by chenrui333** [nickg/nvc#421]
👋  trying to upgrade the formula to the latest release build, but runs into some error as below:

```
** Fatal: access: /usr/local/Cellar/nvc/1.5.2/share/nvc/std/_NVC_LIB: Operation not permitted
```

relates to Homebrew/homebrew-core#82232

**Comment by nickg** [comment]
How can I reproduce this? I tried:

```
brew install --build-from-source ./nvc.rb
```

With the `nvc.rb` from the linked PR and it worked fine.

**Comment by nickg** [comment]
Never mind, it fails with `brew test ./nvc.rb`. I'm not very familiar with macOS but it seems when running under `sandbox-exec`, `access(2)` can fail with `EPERM` (contrary to what the man page says). You should be able to apply 64c25212 as a patch to work around this.

**Comment by chenrui333** [comment]
@nickg the patch works for me, thanks!!
