### ISSUE TITLE
Parallel files analysis

### ISSUE THREAD

**Issue by m-kru** [nickg/nvc#470]
Is it safe to analyze files belonging to the same library in parallel? Is it the same in case of analyzing files belonging to different libraries?

**Comment by nickg** [comment]
Yes it's completely safe: accesses to a library are protected by a reader/writer lock in the filesystem (using `flock` on POSIX or `LockFileEx` on Windows) which allow multiple concurrent readers or a single writer. `make bootstrap -j` works fine for example and if you calculate the SHAs of the library files you'll always get the same result (so builds are reproducible when run in parallel).

I can add a note to the man page about this.

**Comment by m-kru** [comment]
But within the library user still needs to keep the valid order of files analysis?

**Comment by nickg** [comment]
You need to analyse the files in the proper dependency order: e.g. an entity before its architecture. But if two files in a library are independent you can analyse them in parallel (i.e. there won't be any data corruption or other issues).
