### ISSUE TITLE
Imply the standard revision on elaborate and run.

### ISSUE THREAD

**Issue by m-kru** [nickg/nvc#472]
If there is no `--std` provided explicitly to the elaborate or run command, the following error is displayed:
```
design unit was analysed using standard revision 2008 which is more recent that the currently selected standard 1993
```
Can't the standard be implicitly set during the elaboration or run? Why does one need to set it explicitly if it is already known.

**Comment by nickg** [comment]
It's a reasonable request. I've implemented it above.
