### ISSUE TITLE
uc_mcontext is architecture-specific

### ISSUE THREAD

**Issue by wegank** [nickg/nvc#473]
As title. As a result, lines 730-734 in `src/util.c`
```
#if defined __linux__
   STATIC_ASSERT(__NGREG <= MAX_CPU_REGS);
   for (int i = 0; i < MAX_CPU_REGS; i++)
      regs[i] = (i < __NGREG) ? uc->uc_mcontext.gregs[i] : 0;
#else
```
do not compile on aarch64-linux.

**Comment by nickg** [comment]
I've been meaning to refactor this code for a while. It should support some more common platforms now, including Linux/AArch64.
