### ISSUE TITLE
Use stderr for errorlevel error and higher

### ISSUE THREAD

**Issue by avelure** [nickg/nvc#491]
This is more of a feature request, but I noticed that all reports with a severity is sent to stderr, even for "note". This makes it a bit problematic for a program I have that parses the output for errors from the simulator. 
Would it be possible to only send errorlevel error and higher to stderr, or have the level as an option? This also would apply for analysis so that one can choose to filter warnings.

**Comment by nickg** [comment]
I could add an option `--stderr=level` where `level` and above go to stderr and everything else to stdout?

**Comment by avelure** [comment]
That would be perfect, thanks!

**Comment by nickg** [comment]
This is done now, try `--stderr=error`.
