### ISSUE TITLE
fatal: iteration limit of 1000 delta cycles reached

### ISSUE THREAD

**Issue by avelure** [nickg/nvc#521]
Would it be an idea to add a hint that the value can be changed with [--stop-delta=N](https://www.nickg.me.uk/nvc/manual.html#-stop-delta)?
The value is a bit low compared to ghdl (5000) and modelsim (10e6) I haven't happened upon it before. The manual also doesn't mention about iterations, so it took me a while to find the right one.

**Comment by nickg** [comment]
There is actually a hint at the moment but it's not printed with the compact message style:

```
** Fatal: iteration limit of 1000 delta cycles reached
** Note: You can increase this limit with --stop-delta
```

I've tweaked the message a bit to remove the word "iteration" and increased the default limit to 10000.
