### ISSUE TITLE
Minor: existing library directories

### ISSUE THREAD

**Issue by amb5l** [nickg/nvc#548]
I am using nvc --init to create library directories. It would be helpful (in the context of OSVVM) if a command line option could be added to prevent the normal error where a directory exists:
`** Fatal: directory XXX already exists and is not an NVC library`

My suggestion would be: add --reinit option to accept existing empty directories and wipe any existing content. Otherwise identical to --init, and works the same if there is no existing directory/content.

**Comment by nickg** [comment]
I've downgraded this error to a warning as it caused other issues (#746).
