### ISSUE TITLE
NVC Version seems to have broken

### ISSUE THREAD

**Issue by JimLewis** [nickg/nvc#664]
I installed a newer version of NVC from the Actions artifacts for MSYS2.   When I run 
nvc --version

It generates an error.    Are these not suitable for installing under MSYS2? 

Are there newer versions available somewhere other than Actions/artifacts?   I note that it has been a while since https://github.com/nickg/nvc/releases was updated.

**Comment by nickg** [comment]
The description got lost somewhere?

**Comment by JimLewis** [comment]
Updated MSYS2 per 663
