### ISSUE TITLE
Stack corruption with large number of arguments

### ISSUE THREAD

**Issue by JimLewis** [nickg/nvc#665]
What does this message mean?   I am using one of the newer releases from the artifacts of the Actions.

Error: *** stack smashing detected ***: terminated
Error: child killed: unknown signal

**Comment by nickg** [comment]
It's a bug in the simulator. Is there a way I can reproduce this?

**Comment by nickg** [comment]
> It's a bug in the simulator. Is there a way I can reproduce this?

Never mind, I know what causes this.

**Comment by nickg** [comment]
I also fixed this on the 1.9 release branch. There's MSYS2 binaries here: https://github.com/nickg/nvc/suites/12413426002/artifacts/660285668
