### ISSUE TITLE
Using a string match in if generate statement messes up in elaboration

### ISSUE THREAD

**Issue by nicholasjoukh** [nickg/nvc#707]
[nvc_string_with_gen_test.zip](https://github.com/nickg/nvc/files/11631037/nvc_string_with_gen_test.zip)

Looks like a part of elaboration isn't string matching properly. It complains about the else statement when the generic is a string, but it works when the generic is a boolean. It's fine when you run the sim (i.e. the code can be elaborated), the expected value is correct.
```
library ieee;
use ieee.std_logic_1164.all;

entity test_module is
    generic (
        CONDITION : string := "true"
    );
    port (
        output : out std_logic_vector
    );
end entity test_module;

architecture rtl of test_module is

begin
    bad_cond : if CONDITION = "true" generate
        output <= X"12";
    else generate
        output <= X"1234";
    end generate;
end architecture;
```
The sim passes an 8 wide logic vector to the module (which is what elaboration complains about)

**Comment by nickg** [comment]
The problem is elaboration does a static bounds check after it's determined the bounds for the unconstrained port but before it's elaborated the generate statement. Should be fixed now.
