### ISSUE TITLE
Githash in version output

### ISSUE THREAD

**Issue by avelure** [nickg/nvc#813]
It looks like that after the change to v1.12-devel the information of the githash that the version was built from disappeared, is this intentional?

```
nvc 1.12-devel () (Using LLVM 15.0.7)
Copyright (C) 2011-2023  Nick Gasson
This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
you are welcome to redistribute it under certain conditions. See the GNU
General Public Licence for details.
```
previously
```
nvc 1.11-devel (1.10.0.r331.g3f21c263) (Using LLVM 15.0.7)
Copyright (C) 2011-2023  Nick Gasson
This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
you are welcome to redistribute it under certain conditions. See the GNU
General Public Licence for details.
```

**Comment by nickg** [comment]
It's not intentional. The command the makefile runs to generate that is `git describe --long | sed 's/^r\(.*\)/\1/; s/\([^-]*-g\)/r\1/;s/-/./g'` could you try running that and/or `git describe --long` and see what it prints?

**Comment by avelure** [comment]
I think this is related to a change in my docker build script.
I changed the repo checkout to be `git clone --depth=1 https://github.com/nickg/nvc.git` to speed up the checkout.
As this doesn't check out the commits since the last tag, then I guess git can not count them to present them with `describe`
```
root@4d64c00ba9d9:/tmp/nvc# git describe --long
fatal: No names found, cannot describe anything.
```

**Comment by nickg** [comment]
Found a simple solution is to just add `--always` to the `git describe` command. Now it prints:

```
nvc 1.12-devel (2025713e16a9) (Using LLVM 14.0.6)
```
