### ISSUE TITLE
Boolean typed signals written as 1 bit vectors on the FST output

### ISSUE THREAD

**Issue by augustofg** [nickg/nvc#897]
I've been experimenting with [Surfer](https://gitlab.com/surfer-project/surfer) and it didn't like the way NVC represents boolean signals on FST files. [Here is the issue I've opened](https://github.com/ekiwi/wellen/issues/16#issuecomment-2163793570) on [wellen](https://github.com/ekiwi/wellen) (the waveform file parser used in Surfer). The author implemented a workaround to avoid crashing wellen, but it may be better to use the same strategy that GHDL uses (enum type).

**Comment by nickg** [comment]
I tried this in the commit above and it works with Surfer and the master branch of GtkWave, but  GtkWave v3.3.114 (the current release in Debian) crashes with:

```
FSTLOAD | Internal error, nonsequential enum tables definition encountered, exiting.
```

So I've left it disabled for now.
