### ISSUE TITLE
MSYS-clang prefer clang compiler

### ISSUE THREAD

**Issue by avelure** [nickg/nvc#936]
We had an issue setting up a new msys environment to compile nvc.
As configure complains of not finding a compiler, the user installed gcc as it was listed with "no" in the list. gcc is only available from msys/gcc.
Then when the configure later complained that llvm was missing, the user installed it from clang64/mingw-w64-clang-x86_64-clang. There is however also a msys/llvm, but it is only version 11 and in clang it is 18.
When running again, configure gives a slightly different error that llvm-config is not present, even though it can be executed. 
Providing the "--with-llvm=/clang64/bin/llvm-config" parameter has no effect on the message.
We compared with another setup and noticed clang was missing, so we added clang64/mingw-w64-clang-x86_64-clang, but the error is still the same.
The solution was to uninstall msys/gcc.
I guess maybe the "--with-system-cc=" could have been used if we knew the problem was a mismatch between the compiler that was selected by configure and the compiler used to build the llvm that was installed. 

Would it be possible to preference and require clang on msys-clang?

**Comment by nickg** [comment]
This is also a problem in UCRT and MinGW x64 if msys/gcc is installed but the UCRT/MinGW gcc is not. I think it would be best to generate an error from configure if `$CC -dumpmachine` reports "x86_64-pc-msys" (Clang is "x86_64-w64-windows-gnu" and MinGW x64 is "x86_64-w64-mingw32".
