### ISSUE TITLE
array of record causes runtime failure

### ISSUE THREAD

**Issue by hyOzd** [nickg/nvc#95]
Declaring an array of record causes a runtime failure. Below is an example:

    library ieee;
    use ieee.std_logic_1164.all;
    
    entity tb_test_record_array is
    end entity;
    
    architecture behav of tb_test_record_array is
    
        type point is record
            x : integer;
            y : integer;
        end record point;
    
        type point_array is array(0 to 4) of point;
        signal points : point_array := (others => (x => 1, y => 1));
    
    begin
        process
        begin
            wait;
        end process;
    end behav;

Here is the output of `nvc` when run with `--trace` option.

    TRACE (init): _set_initial :tb_test_record_array:points values=01000000010000000100000001000000010000000100000001000000010000000100000001000000 nparts=1 index=2
    nvc: ../src/rt/rtkern.c:540: _set_initial: Assertion `remain >= g->length' failed.
    
    *** Caught signal 6 (SIGABRT) ***
    
    -------- STACK TRACE --------
    /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f2f31ef0bb9]
    /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f2f31ef0bb9]
    /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f2f31ef3fc8]
    /lib/x86_64-linux-gnu/libc.so.6(+0x2fa76) [0x7f2f31ee9a76]
    /lib/x86_64-linux-gnu/libc.so.6(+0x2fb22) [0x7f2f31ee9b22]
    nvc(_set_initial+0x3ef) [0x4655cf]
    [0x7f2f34eca05f]
    -----------------------------

**Comment by nickg** [comment]
Fixed, finally!

**Comment by hyOzd** [comment]
Thanks, Nick.
