### ISSUE TITLE
Runtime Crash -  Fatal: invalid type kind T_ARRAY in range_of

### ISSUE THREAD

**Issue by tasgomes** [nickg/nvc#953]
I found another case that makes NVC to crash. I tried to remove all unnecessary code to reproduce the crash and ended up with this [nvc_bug_4.zip](https://github.com/user-attachments/files/16710890/nvc_bug_4.zip). This is enough to crash NVC while it runs on GHDL, Questa and Modelsim.

![image](https://github.com/user-attachments/assets/4cb6c6f6-d14a-4489-aba2-ffaa087b807e)

To reproduce open a console, go to folder fw, and execute:
python3 -u ./sim/run.py -o ./sim/vunit_out/nvc --simulator nvc --simulator-path C:/NVC_1_13_2/bin --vendor-lib ./fw/sim/sim_lib/nvc

Please adapt the path of the NVC installation folder in the command above (see --simulator-path).

NVC 1.13.2.

**Comment by nickg** [comment]
This set of bugs should all be fixed in the latest 1.13.3 release.

**Comment by tasgomes** [comment]
Thank you!
