### ISSUE TITLE
Internal DUT signal aliasing, file parsing/elaboration error

### ISSUE THREAD

**Issue by p-kuzmanovic** [nickg/nvc#964]
I experienced an issue with fetching internal DUT signals in my TB:
![image](https://github.com/user-attachments/assets/c156de47-76cb-4a5d-9024-95b2668bd976)

It's difficult to share the code, but it seems easy to reproduce the issue.

Just by **moving** the DUT instantiation to be **above** the process that fetches the internal DUT signal the **error disappears**.

It seems like an issue with file parsing and elaboration.

**Comment by nickg** [comment]
Could you test again with the latest master branch?

**Comment by nickg** [comment]
Should be fixed now.

**Comment by p-kuzmanovic** [comment]
Sorry, I haven't been able to test the fix yet. I think I will wait for the next release and give it a try then. Thanks!
