### ISSUE TITLE
wrong gpg verify command?

### ISSUE THREAD

**Issue by NikLeberg** [nickg/nvc#981]
If I run gpg verification of the tarball:

```bash
$ gpg --verify $NV_TARBALL    
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

Then I get the given error. So I'm assuming that the below documented command:

https://github.com/nickg/nvc/blob/d3decdb51a4d2b832fbccc3e9a94221b1f5c40b2/www/download.html.in#L22

should be changed to:

```
gpg --verify `nvc-'__version`.tar.gz.sig' 
```

Thanks.

**Comment by nickg** [comment]
Yes the download page is wrong, thanks.
