### ISSUE TITLE
Associate pure and impure functions

### ISSUE THREAD

**Issue by erick166** [nickg/nvc#990]
I'm using a package which has a generic pure function input and I want to use an impure function as an input, however I get the following error:

error: cannot associate impure function xxx with pure generic subprogram xxx
Error: Program ended with exit code 1

I know this is not fully correct, but could it maybe be a warning instead or what are the implications? I tested with other simulators and they seem to give a warning but still work.

The case is similar to this:
https://stackoverflow.com/questions/66300897/pure-and-impure-functions-whats-the-point

**Comment by nickg** [comment]
I made it a warning with `--relaxed`.
